# Generated by Django 4.2.20 on 2025-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='placeholder', upload_to='', verbose_name='image'),
        ),
    ]
