# Generated by Django 4.2.20 on 2025-03-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_customercomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercomment',
            options={'ordering': ['created_on']},
        ),
    ]
