# Generated by Django 4.2.20 on 2025-03-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_customercomment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercomment',
            old_name='meal',
            new_name='menu',
        ),
    ]
