# Generated by Django 4.2.20 on 2025-03-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_meal_customercomment_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercomment',
            old_name='menu',
            new_name='meal',
        ),
    ]
