# Generated by Django 4.2.20 on 2025-03-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_menu_customercomment_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercomment',
            name='rating',
        ),
        migrations.AddField(
            model_name='customercomment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
