# Generated by Django 4.2.20 on 2025-03-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_customercomment_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercomment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='customercomment',
            name='rating',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
