# Generated by Django 4.2.20 on 2025-03-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_customercomment_options_customercomment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomment',
            name='rating',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
