# Generated by Django 4.2.20 on 2025-03-13 17:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_customercomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
