# Generated by Django 4.2.20 on 2025-03-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='image',
            new_name='featured_image',
        ),
    ]
