# Generated by Django 4.2.20 on 2025-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_rename_image_menu_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='featured_image',
            field=models.ImageField(default='placeholder', upload_to='', verbose_name='image'),
        ),
    ]
