# Generated by Django 4.2.20 on 2025-03-14 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0011_alter_menu_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Ordered'), (1, 'Preparing'), (2, 'Done')], default=0)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to=settings.AUTH_USER_MODEL)),
                ('meal_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_order', to='menu.menu')),
            ],
        ),
    ]
