# Generated by Django 4.2.20 on 2025-03-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
